apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbt
  template:
    metadata:
      labels:
        app: dbt
    spec:
      containers:
      - name: dbt
        image: fishtownanalytics/dbt:latest
        command: ["sleep", "infinity"]
        # Adjust the command as needed to run your dbt jobs or use a Kubernetes Job for one-off runs.
