apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbt
  template:
    metadata:
      labels:
        app: dbt
    spec:
      containers:
      - name: dbt
        # Updated the image reference to the new repository with a valid tag.
        # Change "1.9-bigquery" to the tag that matches your requirements.
        image: xemuliam/dbt:1.9-bigquery
        command: ["sleep", "infinity"]
