apiVersion: v1
kind: Service
metadata:
  name: dbt
spec:
  selector:
    app: dbt
  ports:
    - name: http
      protocol: TCP
      port: 9090       # Service port
      targetPort: 7070 # Container port
  type: NodePort
