apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: apache/superset:latest
        ports:
        - containerPort: 8088
        env:
        - name: SUPERSET_ENV
          value: "production"
        - name: SUPERSET_DATABASE_URI
          value: "postgresql://superset:superset@postgres:5432/superset"
        - name: SUPERSET_CONFIG_PATH  # ✅ Explicitly set the config file path
          value: "/etc/superset/superset_config.py"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: superset-secret
              key: secret_key
        volumeMounts:
          - name: superset-config
            mountPath: /etc/superset  # ✅ Mounting the file
            subPath: superset_config.py  # ✅ Ensuring it's a file
      volumes:
        - name: superset-config
          configMap:
            name: superset-config
---
apiVersion: v1
kind: Service
metadata:
  name: superset
spec:
  type: NodePort
  selector:
    app: superset
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    nodePort: 30088
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
data:
  superset_config.py: |
    import os
    SQLALCHEMY_DATABASE_URI = "postgresql://superset:superset@postgres:5432/superset"
    SECRET_KEY = os.getenv("SECRET_KEY", "your_secret_key")
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-secret
type: Opaque
data:
  secret_key: eW91cl9zZWNyZXRfa2V5  # Base64 encoded value of "your_secret_key"
