---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: apache/superset:latest
        ports:
        - containerPort: 8088
        env:
        - name: SUPERSET_ENV
          value: "production"
        - name: SUPERSET_DATABASE_URI
          value: "postgresql+psycopg2://superset:superset@host.docker.internal:5432/superset"
        - name: SUPERSET_CONFIG_PATH
          value: "/etc/superset"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: superset-secret
              key: secret_key
        - name: PORT
          value: "8088"
        volumeMounts:
        - name: superset-config
          mountPath: /etc/superset
          subPath: superset_config.py
        # The command initializes the DB, creates an admin user, and starts the server.
        # Note: Adjust the command if necessary for idempotence and production use.
        command:
          - sh
          - -c
          - |
            pip install psycopg2-binary && \
            pip install pillow && \
            superset db upgrade && \
            superset init && \
            superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@example.com --password admin && \
            superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
        resources:
          requests:
            memory: "1Gi"  # Minimum memory needed to run the container
            cpu: "500m"    # Minimum CPU needed to run the container
          limits:
            memory: "2Gi"  # Maximum memory the container can consume
            cpu: "1"       # Maximum CPU the container can consume
      volumes:
      - name: superset-config
        configMap:
          name: superset-config
---
apiVersion: v1
kind: Service
metadata:
  name: superset
spec:
  type: NodePort
  selector:
    app: superset
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    nodePort: 30088
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
data:
  superset_config.py: |
    import os
    SQLALCHEMY_DATABASE_URI = "postgresql+psycopg2://superset:superset@host.docker.internal:5432/superset"
    SECRET_KEY = os.getenv("SECRET_KEY", "your_secret_key")
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-secret
type: Opaque
data:
  # Base64 encoded value of "your_secret_key"
  secret_key: eW91cl9zZWNyZXRfa2V5
